---
provisioner:
  name: chef_solo
  require_chef_omnibus: 13.1.31

platforms:
  - name: ubuntu-16.04
    driver:
      name: vagrant
      box: ubuntu/xenial64
      customize:
        memory: 2048
      box_url: https://atlas.hashicorp.com/ubuntu/xenial64
      network:
      #- ["forwarded_port", {guest: 9200, host: 9200}]

suites:
  - name: mytestserver
    run_list: recipe[mytestserver]
    attributes: