name             'mytestserver'
maintainer       'Marco Moscatiello'
maintainer_email 'marco.moscatiello@icloud.com'
license          'All rights reserved'
description      'Installs/Configures mytestserver'
long_description 'Installs/Configures mytestserver'
version          '0.1.0'
